In [68]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import sklearn

In [69]:
import pandas as pd
data = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/housing_data_08-02-2021.csv')
data.head()

,location,district,rooms,size,level,max_levels,price
0,"город Ташкент, Юнусабадский район, Юнусабад 8-...",Юнусабадский,3,57,4,4,52000
1,"город Ташкент, Яккасарайский район, 1-й тупик ...",Яккасарайский,2,52,4,5,56000
2,"город Ташкент, Чиланзарский район, Чиланзар 2-...",Чиланзарский,2,42,4,4,37000
3,"город Ташкент, Чиланзарский район, Чиланзар 9-...",Чиланзарский,3,65,1,4,49500
4,"город Ташкент, Чиланзарский район, площадь Актепа",Чиланзарский,3,70,3,5,55000

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7565 entries, 0 to 7564
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    7565 non-null   object
 1   district    7565 non-null   object
 2   rooms       7565 non-null   int64
 3   size        7565 non-null   object
 4   level       7565 non-null   int64
 5   max_levels  7565 non-null   int64
 6   price       7565 non-null   object
dtypes: int64(3), object(4)
memory usage: 413.8+ KB

In [39]:
data.describe()

             rooms        level   max_levels
count  7565.000000  7565.000000  7565.000000
mean      2.625644     3.699273     6.038202
std       1.085201     2.237275     2.613271
min       1.000000     1.000000     1.000000
25%       2.000000     2.000000     4.000000
50%       3.000000     3.000000     5.000000
75%       3.000000     5.000000     9.000000
max      10.000000    19.000000    25.000000

In [40]:
data.isnull().sum()

location      0
district      0
rooms         0
size          0
level         0
max_levels    0
price         0
dtype: int64

In [41]:
data['price']

0       52000
1       56000
2       37000
3       49500
4       55000
        ...
7560    24500
7561    32000
7562    40000
7563    11000
7564    22914
Name: price, Length: 7565, dtype: object

In [42]:
data['price'].str.replace('Договорная', 'NaN')

0       52000
1       56000
2       37000
3       49500
4       55000
        ...
7560    24500
7561    32000
7562    40000
7563    11000
7564    22914
Name: price, Length: 7565, dtype: object

In [49]:
data['size'].str.replace('Площадьземли:1сот', '0').astype(float)

0       57.0
1       52.0
2       42.0
3       65.0
4       70.0
        ...
7560    38.0
7561    49.0
7562    64.0
7563    18.0
7564    30.0
Name: size, Length: 7565, dtype: float64

In [50]:
def data_clean(df):
    df['price'] = df['price'].str.replace('Договорная', '0')
    df['price'] = df['price'].fillna(method='bfill')
    df['price'] = df['price'].astype(int)
    df['size'] = df['size'].str.replace('Площадьземли:1сот', '0').astype(float)
    return df

In [51]:
data = data_clean(data)

In [53]:
data.describe()

             rooms          size        level   max_levels         price
count  7565.000000   7565.000000  7565.000000  7565.000000  7.565000e+03
mean      2.625644    113.254017     3.699273     6.038202  7.040069e+04
std       1.085201   1491.214078     2.237275     2.613271  6.363698e+05
min       1.000000      0.000000     1.000000     1.000000  0.000000e+00
25%       2.000000     50.000000     2.000000     4.000000  3.450000e+04
50%       3.000000     66.000000     3.000000     5.000000  4.600000e+04
75%       3.000000     86.000000     5.000000     9.000000  6.600000e+04
max      10.000000  70000.000000    19.000000    25.000000  5.200000e+07

In [56]:
data['district'].value_counts()

Чиланзарский         1641
Мирзо-Улугбекский    1382
Юнусабадский          883
Учтепинский           880
Мирабадский           773
Яккасарайский         658
Яшнободский           484
Шайхантахурский       396
Олмазорский           269
Сергелийский          175
Янгихаётский           16
Бектемирский            8
Name: district, dtype: int64

In [58]:
from sklearn.preprocessing import OrdinalEncoder 

ordinal = OrdinalEncoder()
joylashuv_category_encoded = ordinal.fit_transform(data[['district']])
joylashuv_category_encoded[:10]

array([[8.],
       [9.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [9.],
       [5.],
       [6.]])

In [60]:
data['joylashuv_to_number'] = pd.DataFrame(joylashuv_category_encoded)

In [61]:
data

,location,district,rooms,size,level,max_levels,price,joylashuv_to_number
0,"город Ташкент, Юнусабадский район, Юнусабад 8-...",Юнусабадский,3,57.0,4,4,52000,8.0
1,"город Ташкент, Яккасарайский район, 1-й тупик ...",Яккасарайский,2,52.0,4,5,56000,9.0
2,"город Ташкент, Чиланзарский район, Чиланзар 2-...",Чиланзарский,2,42.0,4,4,37000,6.0
3,"город Ташкент, Чиланзарский район, Чиланзар 9-...",Чиланзарский,3,65.0,1,4,49500,6.0
4,"город Ташкент, Чиланзарский район, площадь Актепа",Чиланзарский,3,70.0,3,5,55000,6.0
...,...,...,...,...,...,...,...,...
7560,"город Ташкент, Яшнободский район, Городок Авиа...",Яшнободский,1,38.0,5,5,24500,11.0
7561,"город Ташкент, Яшнободский район, 1-й проезд А...",Яшнободский,2,49.0,1,4,32000,11.0
7562,"город Ташкент, Шайхантахурский район, Зульфиях...",Шайхантахурский,2,64.0,3,9,40000,7.0
7563,"город Ташкент, Мирзо-Улугбекский район, Буюк И...",Мирзо-Улугбекский,1,18.0,1,4,11000,2.0
7564,"город Ташкент, Чиланзарский район, Чиланзар 6-...",Чиланзарский,1,30.0,2,4,22914,6.0

In [63]:
column = ['rooms',	'size',	'level',	'max_levels',	'price',	'joylashuv_to_number']
data_number = data[column]

In [64]:
data_number

      rooms  size  level  max_levels  price  joylashuv_to_number
0         3  57.0      4           4  52000                  8.0
1         2  52.0      4           5  56000                  9.0
2         2  42.0      4           4  37000                  6.0
3         3  65.0      1           4  49500                  6.0
4         3  70.0      3           5  55000                  6.0
...     ...   ...    ...         ...    ...                  ...
7560      1  38.0      5           5  24500                 11.0
7561      2  49.0      1           4  32000                 11.0
7562      2  64.0      3           9  40000                  7.0
7563      1  18.0      1           4  11000                  2.0
7564      1  30.0      2           4  22914                  6.0

[7565 rows x 6 columns]

# min max formula

In [65]:
from sklearn.preprocessing import MinMaxScaler 

min_max_data = MinMaxScaler()
min_max_data.fit_transform(data_number)

array([[2.22222222e-01, 8.14285714e-04, 1.66666667e-01, 1.25000000e-01,
        1.00000000e-03, 7.27272727e-01],
       [1.11111111e-01, 7.42857143e-04, 1.66666667e-01, 1.66666667e-01,
        1.07692308e-03, 8.18181818e-01],
       [1.11111111e-01, 6.00000000e-04, 1.66666667e-01, 1.25000000e-01,
        7.11538462e-04, 5.45454545e-01],
       ...,
       [1.11111111e-01, 9.14285714e-04, 1.11111111e-01, 3.33333333e-01,
        7.69230769e-04, 6.36363636e-01],
       [0.00000000e+00, 2.57142857e-04, 0.00000000e+00, 1.25000000e-01,
        2.11538462e-04, 1.81818182e-01],
       [0.00000000e+00, 4.28571429e-04, 5.55555556e-02, 1.25000000e-01,
        4.40653846e-04, 5.45454545e-01]])

In [73]:
data[data['price'] == 'Договорная']

,location,district,rooms,size,level,max_levels,price
202,"город Ташкент, Яккасарайский район, Баходыра",Яккасарайский,3,119,3,9,Договорная
411,"город Ташкент, Яккасарайский район, Баходыра",Яккасарайский,4,160,4,9,Договорная
439,"город Ташкент, Мирзо-Улугбекский район, улица ...",Мирзо-Улугбекский,3,105,5,6,Договорная
460,"город Ташкент, Чиланзарский район, Чиланзар 1-...",Чиланзарский,3,90,6,8,Договорная
507,"город Ташкент, Яшнободский район, 1-й проезд А...",Яшнободский,2,48,4,4,Договорная
...,...,...,...,...,...,...,...
7039,"город Ташкент, Яшнободский район, Городок Авиа...",Яшнободский,1,38.70,3,8,Договорная
7196,"город Ташкент, Чиланзарский район, Чиланзар-16",Чиланзарский,2,51,3,4,Договорная
7323,"город Ташкент, Мирзо-Улугбекский район, жилой ...",Мирзо-Улугбекский,6,208,1,7,Договорная
7403,"город Ташкент, Учтепинский район, Чиланзар 14-...",Учтепинский,2,35,2,9,Договорная
7404,"город Ташкент, Учтепинский район, Чиланзар 14-...",Учтепинский,2,35,2,9,Договорная